### PR TITLE
#61 wrong error casting

### LINKED ISSUE #61: Response as error type has wrong casting.
On other types of error, that are in the catch for the http.request the offered error is sent and at task response body is empty. Casting is to be performed, or optional chaining.

### PR DESCRIPTION
**Pull request by florentinvintila**
Closes #61

When other types of of request fails the original error is retuned and proper casting or optional chaining is required.

### CODE REVIEW

File: commands/http.js [hunk 1]
```diff
@@ -160,6 +160,8 @@ module.exports = {
 
     new HTTPRetryRequest(config, reqURL, opts)
       .then(res => {
+        log.debug("res");
+        log.debug(res);
```
Comment (tlawrie) [inline commands/http.js:164]: Small nitpick. Could we make this similar to the other formats? or similar? Otherwise good to go

```
log.debug(` \n Response: ${res}`);
```

**Review by tlawrie — APPROVED** [review]

**Comment by tlawrie** [comment]
Hey @florentinvintila do you want these merged in?

**Comment by timrbula** [comment]
@florentinvintila I'm using this in a workflow to make internal k8s requests so it looks to be working. Can it be merged in and the corresponding issue closed?

**Comment by florentinvintila** [comment]
> @florentinvintila I'm using this in a workflow to make internal k8s requests so it looks to be working. Can it be merged in and the corresponding issue closed?

@timrbula @tlawrie Do as you please, I will be out for some time and I will continue my work in another PR. Thank you for understanding.

**Comment by tlawrie** [comment]
Awaiting @morarucostel PR review prior to merging

**Review by morarucostel — APPROVED** [review]
